package: dask
user: dask

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-32
  - win-64

engine:
  - python=2.6
  - python=2.7
  - python=3.3
  - python=3.4

before_script:
  - python -V

script:
  - conda build conda.recipe

iotimeout: 120

build_targets: conda

notifications:
  email:
    recipients: ['mrocklin@continuum.io', 'koverholt@continuum.io']
