language: python
sudo: false
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"


install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytest numpy pip toolz pandas pyzmq
  - pip install locket
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install blosc; fi

  # Install dask
  - python setup.py install

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then py.test partd --doctest-modules --verbose; else py.test partd --verbose; fi

notifications:
  email: false
