language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  # install python requirements
  - pip install coveralls --use-mirrors
  - pip install -e .[tests] --use-mirrors

script:
  # finally run tests
  - make ci-test

after_success:
  - coveralls
