language: python
python:
  - 2.7_with_system_site_packages
  - '3.2'
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: '3.2'
    - python: pypy
addons:
  apt:
    packages:
    - libjpeg-dev
    - python-opencv

install:
  - pip install coveralls
  - make setup

script:
  - make test
after_success:
  coveralls
